/** @format */

const applicationsData = {
  allApplications: [
    {
      jobTitle: "Dance Troupe for Corporate Event",
      role: "Actor",
      location: "Gurgaon, Haryana",
      date: "3/4/16",
      status: "Pending Review",
    },
    {
      jobTitle: "Dance Troupe for Corporate Event",
      role: "Actor",
      location: "Gurgaon, Haryana",
      date: "7/27/13",
      status: "Shortlisted",
    },
    {
      jobTitle: "Corporate Ad Shoot",
      role: "Model",
      location: "Mumbai, Maharashtra",
      date: "4/15/20",
      status: "Shortlisted",
    },
    {
      jobTitle: "Film Casting",
      role: "Actor",
      location: "Chennai, Tamil Nadu",
      date: "6/5/22",
      status: "Selected",
    },
    {
      jobTitle: "Reality Show Casting",
      role: "Singer",
      location: "Pune, Maharashtra",
      date: "3/12/23",
      status: "Pending Review",
    },
    {
      jobTitle: "Dance Troupe for Corporate Event",
      role: "Actor",
      location: "Gurgaon, Haryana",
      date: "3/4/16",
      status: "Pending Review",
    },
    {
      jobTitle: "Dance Troupe for Corporate Event",
      role: "Actor",
      location: "Gurgaon, Haryana",
      date: "7/27/13",
      status: "Not Selected",
    },
    {
      jobTitle: "Corporate Ad Shoot",
      role: "Model",
      location: "Mumbai, Maharashtra",
      date: "4/15/20",
      status: "Selected",
    },
    {
      jobTitle: "Film Casting",
      role: "Actor",
      location: "Chennai, Tamil Nadu",
      date: "6/5/22",
      status: "Selected",
    },
    {
      jobTitle: "Dance Troupe for Corporate Event",
      role: "Actor",
      location: "Gurgaon, Haryana",
      date: "3/4/16",
      status: "Pending Review",
    },
    {
      jobTitle: "Dance Troupe for Corporate Event",
      role: "Actor",
      location: "Gurgaon, Haryana",
      date: "7/27/13",
      status: "Not Selected",
    },
    {
      jobTitle: "Corporate Ad Shoot",
      role: "Model",
      location: "Mumbai, Maharashtra",
      date: "4/15/20",
      status: "Selected",
    },
    {
      jobTitle: "Film Casting",
      role: "Actor",
      location: "Chennai, Tamil Nadu",
      date: "6/5/22",
      status: "Selected",
    },
    {
      jobTitle: "Dance Troupe for Corporate Event",
      role: "Actor",
      location: "Gurgaon, Haryana",
      date: "3/4/16",
      status: "Pending Review",
    },
    {
      jobTitle: "Dance Troupe for Corporate Event",
      role: "Actor",
      location: "Gurgaon, Haryana",
      date: "7/27/13",
      status: "Not Selected",
    },
    {
      jobTitle: "Corporate Ad Shoot",
      role: "Model",
      location: "Mumbai, Maharashtra",
      date: "4/15/20",
      status: "Selected",
    },
    {
      jobTitle: "Film Casting",
      role: "Actor",
      location: "Chennai, Tamil Nadu",
      date: "6/5/22",
      status: "Selected",
    },
  ],
  invites: [
    {
      jobTitle: "Music Video",
      role: "Dancer",
      location: "Delhi",
      date: "8/20/21",
      status: "Invited",
    },
    {
      jobTitle: "Music Video",
      role: "Dancer",
      location: "Delhi",
      date: "8/20/21",
      status: "Invited",
    },
    {
      jobTitle: "Music Video",
      role: "Dancer",
      location: "Delhi",
      date: "8/20/21",
      status: "Invited",
    },
    {
      jobTitle: "Music Video",
      role: "Dancer",
      location: "Delhi",
      date: "8/20/21",
      status: "Invited",
    },
    {
      jobTitle: "Music Video",
      role: "Dancer",
      location: "Delhi",
      date: "8/20/21",
      status: "Invited",
    },
    {
      jobTitle: "Music Video",
      role: "Dancer",
      location: "Delhi",
      date: "8/20/21",
      status: "Invited",
    },
    {
      jobTitle: "Music Video",
      role: "Dancer",
      location: "Delhi",
      date: "8/20/21",
      status: "Invited",
    },
    {
      jobTitle: "Music Video",
      role: "Dancer",
      location: "Delhi",
      date: "8/20/21",
      status: "Invited",
    },
    {
      jobTitle: "Music Video",
      role: "Dancer",
      location: "Delhi",
      date: "8/20/21",
      status: "Invited",
    },
    {
      jobTitle: "Music Video",
      role: "Dancer",
      location: "Delhi",
      date: "8/20/21",
      status: "Invited",
    },

    {
      jobTitle: "Music Video",
      role: "Dancer",
      location: "Delhi",
      date: "8/20/21",
      status: "Invited",
    },
    {
      jobTitle: "Music Video",
      role: "Dancer",
      location: "Delhi",
      date: "8/20/21",
      status: "Invited",
    },
  ],
  drafts: [
    {
      jobTitle: "TV Commercial",
      role: "Model",
      location: "Delhi",
      date: "6/12/22",
      status: "Draft",
    },
    {
      jobTitle: "TV Commercial",
      role: "Model",
      location: "Delhi",
      date: "6/12/22",
      status: "Draft",
    },

    {
      jobTitle: "TV Commercial",
      role: "Model",
      location: "Delhi",
      date: "6/12/22",
      status: "Draft",
    },

    {
      jobTitle: "TV Commercial",
      role: "Model",
      location: "Delhi",
      date: "6/12/22",
      status: "Draft",
    },

    {
      jobTitle: "TV Commercial",
      role: "Model",
      location: "Delhi",
      date: "6/12/22",
      status: "Draft",
    },

    {
      jobTitle: "TV Commercial",
      role: "Model",
      location: "Delhi",
      date: "6/12/22",
      status: "Draft",
    },

    {
      jobTitle: "TV Commercial",
      role: "Model",
      location: "Delhi",
      date: "6/12/22",
      status: "Draft",
    },

    {
      jobTitle: "TV Commercial",
      role: "Model",
      location: "Delhi",
      date: "6/12/22",
      status: "Draft",
    },
    {
      jobTitle: "TV Commercial",
      role: "Model",
      location: "Delhi",
      date: "6/12/22",
      status: "Draft",
    },

    {
      jobTitle: "TV Commercial",
      role: "Model",
      location: "Delhi",
      date: "6/12/22",
      status: "Draft",
    },

    {
      jobTitle: "TV Commercial",
      role: "Model",
      location: "Delhi",
      date: "6/12/22",
      status: "Draft",
    },
    {
        jobTitle: "TV Commercial",
        role: "Model",
        location: "Delhi",
        date: "6/12/22",
        status: "Draft",
      },
      {
        jobTitle: "TV Commercial",
        role: "Model",
        location: "Delhi",
        date: "6/12/22",
        status: "Draft",
      },
      {
        jobTitle: "TV Commercial",
        role: "Model",
        location: "Delhi",
        date: "6/12/22",
        status: "Draft",
      },
      {
        jobTitle: "TV Commercial",
        role: "Model",
        location: "Delhi",
        date: "6/12/22",
        status: "Draft",
      },
  ],
  submitted: [
    {
      jobTitle: "Music Video",
      role: "Singer",
      location: "Bangalore, Karnataka",
      date: "3/8/23",
      status: "Submitted",
    },
    {
        jobTitle: "Music Video",
        role: "Singer",
        location: "Bangalore, Karnataka",
        date: "3/8/23",
        status: "Submitted",
      },
      {
        jobTitle: "Music Video",
        role: "Singer",
        location: "Bangalore, Karnataka",
        date: "3/8/23",
        status: "Submitted",
      },
      {
        jobTitle: "Music Video",
        role: "Singer",
        location: "Bangalore, Karnataka",
        date: "3/8/23",
        status: "Submitted",
      },
      {
        jobTitle: "Music Video",
        role: "Singer",
        location: "Bangalore, Karnataka",
        date: "3/8/23",
        status: "Submitted",
      },
      {
        jobTitle: "Music Video",
        role: "Singer",
        location: "Bangalore, Karnataka",
        date: "3/8/23",
        status: "Submitted",
      },
      {
        jobTitle: "Music Video",
        role: "Singer",
        location: "Bangalore, Karnataka",
        date: "3/8/23",
        status: "Submitted",
      },
      {
        jobTitle: "Music Video",
        role: "Singer",
        location: "Bangalore, Karnataka",
        date: "3/8/23",
        status: "Submitted",
      },
      {
        jobTitle: "Music Video",
        role: "Singer",
        location: "Bangalore, Karnataka",
        date: "3/8/23",
        status: "Submitted",
      },
      
  ],
  auditions: [
    {
      jobTitle: "Reality Show",
      role: "Contestant",
      location: "Hyderabad, Telangana",
      date: "2/15/24",
      status: "Audition Scheduled",
    },
    {
        jobTitle: "Reality Show",
        role: "Contestant",
        location: "Hyderabad, Telangana",
        date: "2/15/24",
        status: "Audition Scheduled",
      },
      {
        jobTitle: "Reality Show",
        role: "Contestant",
        location: "Hyderabad, Telangana",
        date: "2/15/24",
        status: "Audition Scheduled",
      },
      {
        jobTitle: "Reality Show",
        role: "Contestant",
        location: "Hyderabad, Telangana",
        date: "2/15/24",
        status: "Audition Scheduled",
      },
      {
        jobTitle: "Reality Show",
        role: "Contestant",
        location: "Hyderabad, Telangana",
        date: "2/15/24",
        status: "Audition Scheduled",
      },
      {
        jobTitle: "Reality Show",
        role: "Contestant",
        location: "Hyderabad, Telangana",
        date: "2/15/24",
        status: "Audition Scheduled",
      },
      {
        jobTitle: "Reality Show",
        role: "Contestant",
        location: "Hyderabad, Telangana",
        date: "2/15/24",
        status: "Audition Scheduled",
      },
      {
        jobTitle: "Reality Show",
        role: "Contestant",
        location: "Hyderabad, Telangana",
        date: "2/15/24",
        status: "Audition Scheduled",
      },
      {
        jobTitle: "Reality Show",
        role: "Contestant",
        location: "Hyderabad, Telangana",
        date: "2/15/24",
        status: "Audition Scheduled",
      },
  ],
  archived: [
    {
      jobTitle: "Ad Shoot",
      role: "Comedian",
      location: "Chennai, Tamil Nadu",
      date: "1/2/21",
      status: "Archived",
    },
  ],
};

export default applicationsData;
